### ISSUE TITLE
BuildTriggerException

### ISSUE THREAD

**Issue by leo-from-spb** [tkirill/tc-bisect#3]
I've installed the plugin, started the server and add a trigger.
Got the following exception:

'''
jetbrains.buildServer.buildTriggers.BuildTriggerException
Hide stacktrace
jetbrains.buildServer.buildTriggers.BuildTriggerException
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker.callTrigger(BuildTriggersChecker.java:76)
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker.access$1100(BuildTriggersChecker.java:24)
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker$BuildTriggersGroup.processTriggers(BuildTriggersChecker.java:3)
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker.triggerBuilds(BuildTriggersChecker.java:71)
at jetbrains.buildServer.serverSide.impl.BuildServerRunner$4.doSomething(BuildServerRunner.java:2)
at jetbrains.buildServer.serverSide.impl.BuildServerRunner$BuildServerWorker.runAction(BuildServerRunner.java:16)
at jetbrains.buildServer.serverSide.impl.BuildServerRunner$BuildServerWorker.run(BuildServerRunner.java:47)
at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
at org.tkirill.teamcity.bisectPlugin.BisectRepository.getAllNotFinished(BisectRepository.java:36)
at org.tkirill.teamcity.bisectPlugin.BisectBuildTriggerHelper.triggerBuild(BisectBuildTriggerHelper.java:26)
at org.tkirill.teamcity.bisectPlugin.BisectBuildTriggerPolicy.triggerBuild(BisectBuildTriggerPolicy.java:27)
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker$4.run(BuildTriggersChecker.java:2)
at jetbrains.buildServer.util.NamedThreadFactory.executeWithNewThreadName(NamedThreadFactory.java:89)
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker.callTrigger(BuildTriggersChecker.java:95)
... 7 more 
'''

**Comment by tkirill** [comment]
@leo-from-spb Many thanks for the bug report!  I should worry you that the plugin is in alpha phase and there may (and will) be a lot of bugs.

However, I haven't seen this error before and I want to reproduce it.  I think this error occurs when there is no data in `CustomDataStorage`.  Hope if it is that simple.  Nevertheless, may I ask you to clarify some details?
- Which version of TeamCity do you have?
- Do you attach build trigger to an existing or to the brand new build configuration?

**Comment by leo-from-spb** [comment]
> Which version of TeamCity do you have?

9.1 build 36849

> Do you attach build trigger to an existing or to the brand new build configuration?

mmm... haven't got the question.

I had a build configuration where the top (latest) build is red. I've stopped the server, installed the plugin, started, the added the trigger to the build configuration. Got that exception.

**Comment by tkirill** [comment]
@leo-from-spb Thank you!  I'll try to reproduce the error and fix it in the next few days.

**Comment by tkirill** [comment]
@leo-from-spb Sorry for delay!  I managed to reproduce the error on fresh build configuration and I think the fix won't be hard.

**Comment by tkirill** [comment]
@leo-from-spb The bug was fixed in [0.2.2](https://github.com/tkirill/tc-bisect/releases/tag/v0.2.2). Could you check if the fix work for you?

**Comment by mmkumaran** [comment]
Hi,

I just tried the 0.2.2 build and i get below exception in the UI. I can see the builds are triggered, but i just see this exception 

jetbrains.buildServer.buildTriggers.BuildTriggerException 

jetbrains.buildServer.buildTriggers.BuildTriggerException 
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker.callTrigger(BuildTriggersChecker.java:91) 
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker.access$1100(BuildTriggersChecker.java:28) 
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker$BuildTriggersGroup.processTriggers(BuildTriggersChecker.java:17)
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker.triggerBuilds(BuildTriggersChecker.java:116) 
at jetbrains.buildServer.serverSide.impl.BuildServerRunner$4.doSomething(BuildServerRunner.java) 
at jetbrains.buildServer.serverSide.impl.BuildServerRunner$BuildServerWorker.runAction(BuildServerRunner.java:5)
at jetbrains.buildServer.serverSide.impl.BuildServerRunner$BuildServerWorker.run(BuildServerRunner.java:41) 
at java.lang.Thread.run(Thread.java:662) 
Caused by: java.lang.NullPointerException 
at org.tkirill.teamcity.bisectPlugin.BisectBuildTriggerHelper.processBisect(BisectBuildTriggerHelper.java:37)
at org.tkirill.teamcity.bisectPlugin.BisectBuildTriggerHelper.triggerBuild(BisectBuildTriggerHelper.java:28) 
at org.tkirill.teamcity.bisectPlugin.BisectBuildTriggerPolicy.triggerBuild(BisectBuildTriggerPolicy.java:27) 
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker$4.run(BuildTriggersChecker.java) 
at jetbrains.buildServer.util.NamedThreadFactory.executeWithNewThreadName(NamedThreadFactory.java:89) 
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker.callTrigger(BuildTriggersChecker.java:39) 
... 7 more
