### ISSUE TITLE
BuildTriggerException on 0.2.2 build

### ISSUE THREAD

**Issue by mmkumaran** [tkirill/tc-bisect#4]
Hi,

I just tried the 0.2.2 build and i get below exception in the UI. I can see the builds are triggered, but i just see this exception in the build config.

jetbrains.buildServer.buildTriggers.BuildTriggerException

jetbrains.buildServer.buildTriggers.BuildTriggerException 
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker.callTrigger(BuildTriggersChecker.java:91) 
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker.access$1100(BuildTriggersChecker.java:28) 
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker$BuildTriggersGroup.processTriggers(BuildTriggersChecker.java:17)
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker.triggerBuilds(BuildTriggersChecker.java:116)
at jetbrains.buildServer.serverSide.impl.BuildServerRunner$4.doSomething(BuildServerRunner.java) 
at jetbrains.buildServer.serverSide.impl.BuildServerRunner$BuildServerWorker.runAction(BuildServerRunner.java:5)
at jetbrains.buildServer.serverSide.impl.BuildServerRunner$BuildServerWorker.run(BuildServerRunner.java:41) 
at java.lang.Thread.run(Thread.java:662) 
Caused by: java.lang.NullPointerException 
at org.tkirill.teamcity.bisectPlugin.BisectBuildTriggerHelper.processBisect(BisectBuildTriggerHelper.java:37)
at org.tkirill.teamcity.bisectPlugin.BisectBuildTriggerHelper.triggerBuild(BisectBuildTriggerHelper.java:28) 
at org.tkirill.teamcity.bisectPlugin.BisectBuildTriggerPolicy.triggerBuild(BisectBuildTriggerPolicy.java:27) 
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker$4.run(BuildTriggersChecker.java) 
at jetbrains.buildServer.util.NamedThreadFactory.executeWithNewThreadName(NamedThreadFactory.java:89) 
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker.callTrigger(BuildTriggersChecker.java:39) 
... 7 more

**Comment by tkirill** [comment]
@mmkumaran Big thanks for bug report!

I'll try to reproduce it on this week.  I already checked the plugin on clean instance of TC when I was fixing #3 and it worked.  I'll try to find what I've missed.

**Comment by erthink** [comment]
One more backtrace from TC 9.1.3:

```
jetbrains.buildServer.buildTriggers.BuildTriggerException
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker.callTrigger(BuildTriggersChecker.java:12)
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker.access$1100(BuildTriggersChecker.java:101)
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker$BuildTriggersGroup.processTriggers(BuildTriggersChecker.java:1)
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker.triggerBuilds(BuildTriggersChecker.java:95)
at jetbrains.buildServer.serverSide.impl.BuildServerRunner$4.doSomething(BuildServerRunner.java:2)
at jetbrains.buildServer.serverSide.impl.BuildServerRunner$BuildServerWorker.runAction(BuildServerRunner.java:34)
at jetbrains.buildServer.serverSide.impl.BuildServerRunner$BuildServerWorker.run(BuildServerRunner.java:37)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
at org.tkirill.teamcity.bisectPlugin.BisectRepository.getAllNotFinished(BisectRepository.java:36)
at org.tkirill.teamcity.bisectPlugin.BisectBuildTriggerHelper.triggerBuild(BisectBuildTriggerHelper.java:26)
at org.tkirill.teamcity.bisectPlugin.BisectBuildTriggerPolicy.triggerBuild(BisectBuildTriggerPolicy.java:27)
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker$4.run(BuildTriggersChecker.java:2)
at jetbrains.buildServer.util.NamedThreadFactory.executeWithNewThreadName(NamedThreadFactory.java:89)
at jetbrains.buildServer.serverSide.impl.BuildTriggersChecker.callTrigger(BuildTriggersChecker.java:50)
... 7 more
```

**Comment by tkirill** [comment]
@leo-yuriev Thanks!  I really need to inspect storage code again.
